### ISSUE TITLE
parameter monitoring

### ISSUE THREAD

**Issue by bernhard-da** [tenderle/ptable#8]
in `pt_create_pTable()`, parameter `monitoring` is not consistently used. you stillt get output printed even when `monitoring=FALSE` is set.

**Comment by tenderle** [comment]
Hi @bernhard-da, the reason is, that there are two different types of output:
- the first one is meant as a feature for users such that they see what happens (monitoring)
- the other one is meant for debugging (debugging, will be removed afterwards)

However, since there may be use cases where such an output is impractical, I did some updates. Within the new version 0.1.8 (i.e., commits ee4bc26035e5ca112ad9446cb2c8df8bf9639a4f, ff210c3e5fa810c46b5d4edb030dc700ae06bf79 and 914558669d3021f7a7281be6f64c6da767a78071) I distinguish between both types via the arguments `monitoring` and `debugging`.
